openapi: 3.0.0
servers: [ ]
info:
  version: "1.0.0-SNAPSHOT"
  title: Interview Test Java
security:
  - application:
      - read
      - write
paths:
  /departments:
    get:
      summary: get the list of departments
      operationId: getDepartments
      tags:
        - "departments"
      responses:
        "200":
          description: departments list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepartmentRead'
components:
  schemas:
    Id:
      type: integer

    DepartmentRead:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
        address:
          type: string
      required:
        - id